- Makefile
- go.mod
- helpers.go
This automatically clones the content repo, from which we get the test
info. This is done by detecting if the ROOT_DIR env variable is empty:
if it's empty, we clone it and set the env variable appropriately.
This also takes into account the `products` dir that's being proposed
[1], so the OCP4 e2e tests will not be affected by this change.
[1] https://github.com/ComplianceAsCode/content/pull/7018
> Clone content repo automatically and use alternative products dir

- e2e_test.go
this will be used for the ocp4-moderate-node profile...
Currently, the Gitlab-based IdP doesn't work on FIPS mode. I'll try
switching to Keycloak later.
> Skip IdP setting on profiles with "moderate" prefix

- e2e_test.go
Now that we're using the keycloak IdP, we can test for the IdP setup.
> Deploy IdP also in moderate profiles

- helpers.go
- resultparser/resultparser.go
- resultparser/resultparser_test.go
This adds a small parser to allow us to compare more
complex rules when evaluating results.
e.g. we could now say something like:
```
default_result: PASS or INCONSISTENT
```
Which could be used for rules that are known to fail due to known issues
in OpenShift.
Right now the syntax allows for the following:
```
FOO
FOO or BAR
FOO or BAR or BAZ
```
This doesn't currenlt validate that we're setting correct and specific
results as defined by Compliance Operator. Though this could be easily
added to the parser.
Is this over-engineered? Yes.
Was a parser like this needed? Probably not
But it was sure fun to code :)
The main use-case is a rule that's been failing every once in a while
with INCONSISTENT... It's already reported [1], but it gets no attention
nor do I expect a fix soon.
[1] …
> Add more complex rule result evaluations

- helpers.go
The previous PR only covered cases where it's divided by roles.
> use result parser on "all roles" as well

- vendor/github.com/openshift/cluster-authentication-operator/test/library/keycloakidp.go
`latest` doesn't work with FIPS.
> Pin keycloak container image to 15.0.1

- e2e_test.go
this is meant to help us debug IdP issues. When the test fails (and it
could be because of the IdP, the cleanup doesn't allow us to get
valuable logs.
> Only clean up IdP if test hasn't failed

- e2e_test.go
Apply manual remediation and auto-generated at the same time may cause issues in the cluster, so let's apply auto-generated remediation first and apply the maual remediation.
> Apply maual remediation after auto-generated remediation

- Makefile
- e2e_test.go
- idp_fix.patch
Applying remediation right after Pool is ready might cause some issues, hence let's add some wait before it applies the remediation. 
And also keep the IdP no matter the test's state, so we can have the log.
Change the Idp test-route termination to passthrough, as we need to provide cert for re-encrypt termination
> Add waiting time before applying manual remediation

- Makefile
- e2e_test.go
This commit works in conjunction with https://github.com/ComplianceAsCode/content/pull/8128, the keycloak deployment keeps falling the CI, we are replacing it with Google IDP.
> Remove IdP Keycloak deployment

- .gitignore
- Makefile
The e2e tests generate a lot of useful debugging information, but it can
overflow tmux buffers. Let's tee the information into a dedicated log
file locally so we can reference it during local runs.
This commit only adds this functionality to the make file target and
also excludes the test log file from the repository. Invoking the tests
manually using `go test` will not generate a log file.
> Stash test results into a file

- README.md
Let's document the basic behavior of the e2e tests and what users should
expect if they attempt to run them.
> Add a README.md with basic usage for running end-to-end tests

- e2e_test.go
- helpers.go
It seems to me that the most recent `Status.Conditions` is appended to the array;
or they are not ordered  at alland we should be checking all of them.
In either case, looking at all the status condition when assessing whether CO is deployed should be enough.
Fixes:
CI runs in witch the `Operator setup` phase fails, but the test continues and seems fine:
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-ComplianceAsCode-content-master-4.16-e2e-aws-ocp4-pci-dss-node-weekly/1761526471932776448
References:
Check the example output in [Failed Deployments](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#failed-deployment)
> Check all Deployment status conditions

- helpers.go
We want the object, not the index, :P
Fixes `./helpers.go:314:12: cond.Type undefined (type int has no field or method Type)`
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/ComplianceAsCode_ocp4e2e/32/pull-ci-ComplianceAsCode-ocp4e2e-main-e2e-aws-ocp4-moderate/1762213976051027968/artifacts/e2e-aws-ocp4-moderate/test/build-log.txt
> Deployment Status Conditions: Fix for loop element

- helpers.go
When waiting for the Deployment to be ready we periodically check for its `Status.Conditions`.
But a flawed logic lead us to return `Errorf` on the first Status.Condition, :sweat_smile: 
Let's check all of them before erroring, :smile:
> Waiting for Deployment: Check all Status.Conditions before erroring

- Makefile
- e2e_test.go
- helpers.go
In some cases, like running the Compliance Operator on managed offerings, we don't want to assert remediation behavior in the tests because it's not guaranteed users have the ability to remediate.
This commit adds a new flag to short-circuit the test if we don't need to test remediations.
> CMP-2473: Implement flag to bypass remediations

- helpers.go
Fix the path we are looking for expected e2e test files, so that we can correct detect if a ocp version is missing expected test file.
> Fixing detecting missing e2e result files

- Makefile
- helpers.go
Having a organized way to manage e2e assertion files, we will have all e2e assertion files located at `tests/assertions/<platform>/<product-name>-<profile-name>-<ocp-version>.yml`
for example `tests/ocp4/assertions/ocp4-cis-4.14.yml`
If there is no assertion file, we will use the old logic to evaluate the rule, and in the end test print out the new formate assertion file in the log. This helps us to bootstrap a new CI assertion file easily.
> Add a new way to do profile rule assertion

- helpers.go
Let's make ocp4 as the default value for the platform
> Make ocp4 a default value for platform

- helpers.go
By default, only worker nodes are accessible in ROSA environments. This
means we need to update the test suite to remove the nodeSelector and
tolerations so that the compliance operator can schedule to worker
nodes. Otherwise, the deployment will wait forever for master nodes to
be available.
> Support deploying CO on managed offerings (ROSA)

- Makefile
- helpers.go
The platform argument was misspelled, causing it to be ignored if you
used it locally with `make e2e`.
> Fix typos in platform argument

- e2e_test.go
- helpers.go
We're hitting issues parsing the profile bundle on ROSA, so let's add
some test logging here to watch the state.
> Add logging for parsing the profile bundle

- helpers.go
Right now, when a remediation times out, the test suite says the command
failed, but only includes a reference to the script that contains the
remediation.
This commit adds the command output and the error so that it's easier to
understand what's going on with the script and why it might be broken.
> Add more details to remediation timeout

- helpers.go
We're seeing timeouts now that we're using `oc adm
wait-for-stable-cluster` as part of the logic to ensure manual
remediations are applied to the cluster.
This commit bumps the context timeout to 1 hour to give the cluster more
time to bounce the cluster operators after the manual remediations are
applied. Otherwise we end up with errors similar to the following:
Error: context deadline exceeded
> Increase timeout for applying manual remediations

- e2e_test.go
Added a 45 seconds wait after Machineconfig pool finishes updates, this is needed because usb-guard service is not up when the rescan happened and failed the check. Also increased max scan failures retry
> Update e2e test suite to wait before kicking a new scan

- helpers.go
When a rule's result doesn't match the expected result, let's also print the phase in which it happened, whether the default result or after remediation is applied.
> Print assertion phase when verifying rule result

- helpers/utilities.go
In the interest of quicker test times, let's increase the maxUnavailable
to 2 for the master node pool and not just the worker node pool since we
scan both in our testing.
> CMP-3385: Include master node pool in rolling update changes
